# **Lecture One: Matrices**
>In this section we are going to look at matrices and how we can work with them in Python.  
We will also look at the differences between the notation in Python and the notation
in mathematics. 

$ \textrm{Def}^{n}: $ A **matrix** is a rectangular array of numbers or symbols arranged in rows by columns. 
$$ A = \begin{bmatrix} a_{00} & a_{01} & a_{02} & a_{03} \\ a_{10} & a_{11} & a_{12} & a_{13} \\ a_{20} & a_{21} & a_{22} & a_{23} \end{bmatrix} $$  
The values of a matrix are called **entries**.

**Note:** Python starts counting at 0.

In [13]:
import numpy as np # Numpy is a module that will help with working with matrices.

A module allows you to logically organize your Python code. Grouping related code into a module makes the code easier to understand and use. A module is a Python object with arbitrarily named attributes that you can bind and reference.

Simply, a module is a file consisting of Python code. A module can define functions, classes and variables. A module can also include runnable code. https://www.tutorialspoint.com/python/python_modules.htm

In [9]:
# This is what we will use for a matrix.
A = np.array([[1, 3, 2, 0], 
              [4, 1, 2, 2], 
              [2, 1, 1, 1]]) 

Below are some good tools to help us work with matrics.  
* np.shape() find the shape is (rows,columns). Comes from numpy. 
* type() tells us the type of object that we are working with. From p]Python
* print() prints in Python 3. (note this is different than Python 2)

In mathematics, a **tuple** is a finite ordered list (sequence) of elements. An n-tuple is a sequence (or ordered list) of n elements, where n is a non-negative integer. There is only one 0-tuple, an empty sequence, or empty tuple, as it is referred to. An n-tuple is defined inductively using the construction of an ordered pair. https://en.wikipedia.org/wiki/Tuple

In [4]:
A_shape = np.shape(A) #Shape will tell us the dimension of the matrix.
print(A)
print(A_shape) # Print the the shape that we named A_shape
print(type(A_shape)) # use type to help see what we are working with 
print(type(A_shape[0]))
A_shape[0] + 4 # We can add the values of the shape to other numbers.

[[1 3 2 0]
 [4 1 2 2]
 [2 1 1 1]]
(3, 4)
<class 'tuple'>
<class 'int'>


7

In [4]:
A # Will print, but not a great practice.

array([[1, 3, 2, 0],
       [4, 1, 2, 2],
       [2, 1, 1, 1]])

In [5]:
print(A) # Note the difference between handwritten and python matrix notation.

[[1 3 2 0]
 [4 1 2 2]
 [2 1 1 1]]


_**Practice 1:**_ Read in the matrix $A = \begin{bmatrix} 1 & 0 & 2 \\ 1 & 2 & 1 \end{bmatrix} $

_**Solution:**_

In [10]:
A = np.array([[1,0,2], [1,2,1]])

Now we want to start looking at how to access the elements, rows and columns of a matrix.

In [11]:
print(A[0]) #Print the first row. Note, counting starts at 0 in python.

[1 0 2]


Below is the $a_{21}$ entry. Math vs Python counting takes a bit of mental gymnastics.

In [14]:
A[0][1] # This is the a_21 entry. Math vs python counting takes a bit of mental gymnastics.

0

In [16]:
print(A.T[0]) # This will extract the first column. The .T is the transpose of the matrix.

[1 1]


In linear algebra, the transpose of a matrix is an operator which flips a matrix over its diagonal, that is it switches the row and column indices of the matrix by producing another matrix denoted as $ \mathbf{A}^T$. https://en.wikipedia.org/wiki/Transpose

or

In [18]:
A[0,:] # The : in Numpy will allow us to cycle through all the values for that row or column.

array([1, 0, 2])

---
_**Practice 2:**_ Read in the matrix $A = \begin{bmatrix} 4 & -1 & 2 \\ 4 & 2 & 1 \end{bmatrix} $. Then
1. Print just the first row.  
2. Print the third column. 
3. Transpose the matrix.  

**Don't forget to comment each line of your code**

_**Solution:**_

---
## **Matrix operations**

Now we are going to look at the three different operations involving matrices  
**Scalar multiplication**, **matrix multiplication**, and **matrix addition**.

### **Scalar multiplication**  
**Scalar multiplication** is the product of all of the entries of the matrix by a scalar value. 

In [21]:
A = np.array([[2,1],
              [-1,6]])

In [22]:
3 * A #Scalar multiplication. We must use *

array([[ 6,  3],
       [-3, 18]])

In [13]:
3A #Bad syntax, but something that we will use in mathematics.

SyntaxError: invalid syntax (<ipython-input-13-87237a605e0b>, line 1)

### **Matrix Addition**
**Matrix addition**  is the binary operation of adding matrices by adding the corresponding entries together.  
> **Note:** that the matrices must have the same shape.</i>

In [27]:
C = np.array([[2, 3, 3, 0],[2, 9, 2, 0],[4, 1, 8, 1]])
print(np.shape(C))
D = np.array([[-1, 3, 2, 12],[3, 1, 2, 2],[2, 1, 1, 1]])
print(np.shape(D))
print(C,'\n \n', D) # Print the matrices with 2 new lines between them. 

(3, 4)
(3, 4)
[[2 3 3 0]
 [2 9 2 0]
 [4 1 8 1]] 
 
 [[-1  3  2 12]
 [ 3  1  2  2]
 [ 2  1  1  1]]


In [28]:
E = C + D
print(E)

[[ 1  6  5 12]
 [ 5 10  4  2]
 [ 6  2  9  2]]


### **Matrix Multiplication**
**Matrix multiplication** of matrices $ \mathbf{A} $ and $ \mathbf{B} $ is a third matrix $ \mathbf{C} $, i.e. $ \mathbf{C} = \mathbf{AB} $ , where $ \mathbf{c}_{ij} $ is the dot  
product of row $i$ of $ \mathbf{A} $ and column $ \mathbf{j} $ of $ \mathbf{B} $. 

Now it is important to note that to multiply matrices they must have a compatable shape. This means that the number columns of the left matrix in the product must match the number of rows of the right matrix in the product.

 $$\begin{array}{c} \begin{bmatrix} 1 & -1 & 1\\ 4 & 2 & 2 \end{bmatrix} \\ 2x3 \end{array} \begin{array}{c}\begin{bmatrix} 3 & 2 \\ -1 & 1 \\ 4 & 2  \end{bmatrix} \\ 3 x 2 \end{array}.$$

---
**NOTATION WARNING**  
Using * to multiply **will not** give use the matrix product. It is a different product.  


In [39]:
print('BAD EXAMPLE')
A * A # AHHHHHHHHHHHHHHH what!!?!? Hadamard product. Not the matrix product.

BAD EXAMPLE


array([[ 1,  1],
       [16,  4]])

---
---
_**Worked Example 1:**_ Multiply $A = \begin{bmatrix} 1 & -1 & 1\\ 4 & 2 & 2 \end{bmatrix} $ by $B = \begin{bmatrix} 3 & 2 \\ -1 & 1 \\ 4 & 2  \end{bmatrix} $.

In [29]:
A = np.array([[1,-1,1],[4,2,2]])

In [30]:
print(np.shape(A))

(2, 3)


So $A$ is a 2$x$3 matrix. So we will need to multiply by a 3$x n$ matrix.

In [31]:
B = np.array([[3,2],[-1,1],[4,2]])

In [32]:
print(np.shape(B))

(3, 2)


At this point we can see that the product matrix will be a $2x2$.

In [35]:
print(np.dot(B,A))
print(np.dot(A,B))

[[11  1  7]
 [ 3  3  1]
 [12  0  8]]
[[ 8  3]
 [18 14]]


So, $\begin{bmatrix} 1 & -1 & 1\\ 4 & 2 & 2 \end{bmatrix} \begin{bmatrix} 3 & 2 \\ -1 & 1 \\ 4 & 2  \end{bmatrix} = \begin{bmatrix} 8 & 3 \\ -18 & 14 \end{bmatrix} $.

---
---
_**Practice 3:**_ Multiply $A = \begin{bmatrix} 1 & -1 \\ 4 & 2 \end{bmatrix} $ by $B = \begin{bmatrix} 3 & 2 \\ -1 & 1 \end{bmatrix} $.

_**Solution:**_

In [36]:
A = np.array([[1,-1],[4,2]])
B = np.array([[3,2],[-1,1]])

print(np.dot(A,B))
print(np.dot(B,A))

[[ 4  1]
 [10 10]]
[[11  1]
 [ 3  3]]


What does Python do if the dimensions are off?  
Let's try and multiply $C = \begin{bmatrix} 1 & -1 \\ 4 & 2 \end{bmatrix} $ by $D = \begin{bmatrix} 3 & 2 \\ -1 & 1 \\ 4 & 2  \end{bmatrix} $.

In [38]:
C = np.array([[1,-1],[4,2]])
D = np.array([[3,2],[-1,1],[4,2]])

np.dot(C,D.T)

array([[ 1, -2,  2],
       [16, -2, 20]])

We can see that we get a **ValueError** and it tells us that that dimensions are off.

$ \textrm{Def}^{n}: $ The **identity matrix** is a square matrix denoted $\mathbf{I}$ that has ones on the main diagonal and zeros everwhere else. The identity for $\mathbb{R}^{3x3}$ is, $I = \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1\\ \end{bmatrix} $.  
Like the number 1, the identity matrix leaves matrices unchanged under matrix multiplication. So,  
$$\mathbf{AI}= \mathbf{IA} = \mathbf{A}$$

---
## Inverse Matrices  
$ \textrm{Def}^{n}: $ The **inverse of a matrix $\mathbf{A}$** is the matrix denoted $\mathbf{A^{-1}}$ such that $\mathbf{AA^{-1}} = \mathbf{A^{-1}A} = \mathbf{I}$.

In [ ]:
from numpy.linalg import inv # import the function inv from numpy.linalg.

In [ ]:
X = np.array([[1,2],[3,4]]) 
Y = np.linalg.inv(x) 

In [ ]:
print(Y)

Now we should check by computing, $\mathbf{XY}$.

In [ ]:
np.dot(X,Y)

In [ ]:
np.dot(Y,X)

Why didn't we get the exact identity?

It should be noted that not all matrices have an inverse. To start, they must be square. In linear algebra we will study the **Invertable Matrix Theorem**. This theorem helps to show all of the connections between invertable matrices and linear algebra. For now we are going to pick one of the connections and use it. https://en.wikipedia.org/wiki/Invertible_matrix 

$ \textrm{Def}^{n}: $ The **determinant** of a matrix is a scalar that can be computed from the entries of a square matrix. https://en.wikipedia.org/wiki/Determinant

**Theorem:** A matrix $\mathbf{A}$ is invertable if and only if $\textrm{det}\mathbf{A} \neq 0$.

__**Worked Example 2:**__ Find the inverse of $C = \begin{bmatrix} 1 & -1 \\ 4 & 2 \end{bmatrix} $

In [ ]:
from numpy.linalg import det

First we check to see that the matrix has an inverse.

In [ ]:
C = np.array([[1,-1],[4,2]])
print('The determinant of C is',np.linalg.det(C))

Cool, so by the theorem, $C$ will have an inverse.

In [ ]:
np.linalg.inv(C)

__**Practice 4:**__ Find the inverse of $W = \begin{bmatrix} 0 & -3 & 2 \\ 1 & -4 & 2 \\ -3 & 4 & 1 \end{bmatrix} $. Check to make sure that it is in fact invertable. (Hint: use the determinant)